###
GET http://localhost:5000/Products HTTP/1.1
Content-Type: application/json; charset=UTF-8
###
GET http://localhost:5000/Products/1 HTTP/1.1
Content-Type: application/json; charset=UTF-8
###
GET http://localhost:5000/Products/4 HTTP/1.1
Content-Type: application/json; charset=UTF-8
